project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: ""
  description: Personal website to showcase past projects and skill sets.
  site-url: "https://rxjiang12.github.io/PORTFOLIO/"
  navbar:
    background: primary
    search: false
    left:
      - text: "Home"
        href: "./index.html"
      - text: "Projects"
        href: "./projects_tab.html"
      - text: "Resume"
        href: "./resume.html"
      - text: "Contact"
        href: "./contact.html"

format:
  html:
    theme: morph
    toc: false

editor:
  mode: source

resources:
  - "Buffalo Flights Data Analysis Folder/fligh_data.html"
  - "RanXinJiangResume.pdf"